### PR TITLE
MOVE: Range from product to cart

### LINKED ISSUE #5: [BUG]: Unable to Reduce Quantities for Multiple Items in Shopping Cart
### Bug Description

When users select multiple quantities of a single item in the shopping cart and later attempt to reduce the quantity for one or more of those items, there is no option available to do so. The system does not provide a way to decrease the quantity of individual items once they have been added to the cart in multiples

### Expected Behavior:
Users should be able to easily decrease the quantity of individual items in the shopping cart when multiple quantities have been selected.

### Actual Behavior:
There is no option available to reduce the quantity of individual items in the shopping cart once multiple quantities have been selected.

### PR DESCRIPTION
**Pull request by bj-jiwrajka**
I've moved the selecting quantity option from product to carditem page. Please check and suggest any changes if required, I would love to work upon it. @Varinder-Dhillon0  closes #5

### CODE REVIEW

**Review by Varinder-Dhillon0 — COMMENTED** [review]
Does total work as expected?  because counter should be multiplied with product price.
Also share me a pic of cart window.

**Comment by bj-jiwrajka** [comment]
> Does total work as expected? because counter should be multiplied with product price. Also share me a pic of cart window.

yes, it works as expected, here are the screenshots:

image
image

**Comment by Varinder-Dhillon0** [comment]
Nice ! and make the + and - borders same as before @bj-jiwrajka

**Comment by bj-jiwrajka** [comment]
> Nice ! and make the + and - borders same as before @bj-jiwrajka

yes sir,I've done it, please check once

**Comment by bj-jiwrajka** [comment]
> > Nice ! and make the + and - borders same as before @bj-jiwrajka
> 
> yes sir,I've done it, please check once

Also, I've formatted the code

**Pull request merged**
