### PR TITLE
feat:Added forgot password using email based approach and also employed jwt tokens and cookies for enhanced security

### PR DESCRIPTION
**Pull request by Niharika0104**
I have implemented a password reset feature using `nodemailer` and` Google App Passwords` for secure email transmission. The process involves generating` JWT` tokens with a 5-minute expiry time and usage of cookies, enhancing security. These tokens are stored in the database for one-time use.

  **Here's how the user interaction flows:**

1.When a user clicks on forgot password,the email input field will be shown.If invalid email address is entered then validation error will be thrown.
2.Upon entering valid email address  a unique JWT token is generated.
3.The user receives an email with a link containing this JWT token.
4.This link is valid for 5 minutes, ensuring a prompt password reset.

**Upon clicking the reset password link:**

1.The server checks for the presence and if JWT token is present in the database then the token was consumed indicating the link has expired.
2.If the token is not found , then the user is directed to the password reset page and token will be added to the database to mark the token as consumed.
3.If the token is found or has expired, a message indicating the link expiration is displayed.

### CODE REVIEW

**Comment by Niharika0104** [comment]
@Varinder-Dhillon0 Please check into this and let me know ,if this is fine?

**Comment by Varinder-Dhillon0** [comment]
There is a flaw if I enter someone else's username and enter my own email for password recovery I can easily change password of someone's id.

**Comment by Niharika0104** [comment]
@Varinder-Dhillon0 usually while registering website ask for email Id.But you website asked for username there is no email field in registration page.If there was email id then we can validate the presence of same email id in the db.If email is present in db we can send mail.Because your not using email field i thought of this approch.Let me know your thoughts on this?

**Comment by Varinder-Dhillon0** [comment]
I think you should remove username and instead add email for making account then on that email jwt token will be sent to reset password or just simply send password on that email

**Comment by Niharika0104** [comment]
I will remove username from signup page and and add email input field with validations.I will changes in db as well if required.On doing so forgot password page will only prompt for emailId.If present email will be sent and yes token will be carried else validation message saying invalid emaild not not regsitered will be thrown.So shall I proceed?

**Comment by Varinder-Dhillon0** [comment]
Yes @Niharika0104

**Comment by Niharika0104** [comment]
@Varinder-Dhillon0  I fixed the issue.Can you check and let me know?

**Comment by Varinder-Dhillon0** [comment]
@Niharika0104  did you test all this code and then made a pr??

**Comment by Varinder-Dhillon0** [comment]
I will check again and get your updates on board @Niharika0104

**Pull request merged**
