### PR TITLE
[Fix] filter sidebar redesigned in search section

### PR DESCRIPTION
**Pull request by EAGLEARCHER**
#116 
Redesign filter sidebar, validate functionalities, and implement responsive design.

### CODE REVIEW

**Comment by Varinder-Dhillon0** [comment]
doesn't look good please make sure there are no changes that removes previous work.

**Comment by EAGLEARCHER** [comment]
Thanks for your feedback. Could you provide more details on what specific elements or aspects you'd like to see preserved in the redesigned filter section to meet your expectations better?

**Comment by Varinder-Dhillon0** [comment]
i want something like this one keep the colors same but change the buttons sizes to small 
image

**Comment by EAGLEARCHER** [comment]
Hey @Varinder-Dhillon0 I have made the respective changes. Please checkout on the #116

**Pull request merged**
